### ISSUE TITLE
Keyboard stopped working altogether after re-install after kernal update

### ISSUE THREAD

**Issue by jbonzo** [SicVolo/hid-apple-3.19#10]
My kernel updated earlier this week and it got rid of the the trackpad and function key fixes. I went back into the folder where I cloned this repo and did 'make' then 'make install'. Then I ran 'sudo update-initramfs -u', rebooted and the keyboard stopped working. External keyboard also stopped working. I'm freaking out.

**Comment by benton** [comment]
Don't panic.

If you still have OS X installed alongside Linux, try holding down the `option` key when the system starts, and boot to OS X. From there, you could install software to mount whatever partition has your grub.conf (or whatever) to select your older, working kernel (it's still there, right?). Or try installing [refind](http://sourceforge.net/projects/refind/) - it's excellent, and will usually discover any existing kernels on the disk.

A potentially easier way is to make an Ubuntu live USB, and try to boot from it (again, by holding down the `option` key). Then do the same thing -- mount your internal disk and configure it to boot from the older, working kernel image.

If OS X has been removed, try holding `CMD`-`option`-`P`-`R` on startup (think of it as an exercise in finger coordination) to zap the system's persistent RAM. I doubt this will affect the keyboard, but it's worth a shot. 

If _none_ of that seems to have any effect on your system's boot behavior, then the keyboard may indeed be damaged. In this case, the system will probably have to be cracked open to recover data and/or restore functionality. But this is pretty unlikely - one of the [Apple boot key sequences](https://support.apple.com/en-us/HT201255) should do _something_.

Good luck.

**Comment by jbonzo** [comment]
What exactly should I do with refind? Also I'm not sure if the kernel is directly my problem. The problem didn't occur right after I updated the kernel. It occurred after I ran sudo update-initramfs -u. Is there a way to revert that action?

**Comment by jbonzo** [comment]
I got it to work. I rolled back the kernel update and now everything is back in order. Thanks for the help benton!
